- .github/workflows/test-app.yml
- README.md
- cpp/CMakeLists.txt
- cpp/Contact.hpp
- cpp/contact_kernels.hpp
- cpp/utils.hpp
- python/setup.py
- python/tests/test_coeffs.py
- python/tests/test_contact_kernels.py
- python/tests/test_dolfinx_cuas.py
Code compatible with https://github.com/Wells-Group/asimov-custom-assemblers/pull/80
> Rewrite for quadraturerule

- cpp/contact_kernels.hpp
- cpp/utils.hpp
https://github.com/Wells-Group/asimov-custom-assemblers/pull/81
> Const declarations

- .github/workflows/test-app.yml
- cpp/Contact.hpp
- cpp/utils.hpp
- python/dolfinx_contact/build_gap_function.py
- python/dolfinx_contact/nitsche_cuas.py
- python/dolfinx_contact/nitsche_rigid_surface_cuas.py
- python/tests/test_coeffs.py
- python/tests/test_contact_kernels.py
- python/tests/test_dolfinx_cuas.py
Fixes issues related to 
FEniCS/basix#317 
FEniCS/ffcx#408
https://github.com/FEniCS/dolfinx/pull/1775
https://github.com/FEniCS/basix/pull/309
> fix failing tests and build errors

- cpp/Contact.hpp
- cpp/utils.hpp
- python/demos/compare_cuas_snes_one_sided.py
- python/demos/compare_nitsche_snes.py
- python/demos/nitsche_euler_bernoulli.py
- python/dolfinx_contact/one_sided/snes_against_plane.py
- python/dolfinx_contact/wrappers.cpp
- python/tests/test_circumradius.py
- python/tests/test_coeffs.py
- python/tests/test_contact_kernels.py
- python/tests/test_nitsche_bc_plane_stress_beam.py
Fixes issues related to https://github.com/FEniCS/dolfinx/pull/1876 and https://github.com/FEniCS/dolfinx/pull/1884
> Some fixes due to changes in dolfinx

- cpp/Contact.hpp
- cpp/utils.hpp
- python/demos/nitsche_euler_bernoulli.py
- python/dolfinx_contact/one_sided/nitsche_ufl.py
- python/dolfinx_contact/one_sided/snes_against_plane.py
- python/tests/test_nitsche_bc_plane_stress_beam.py
Fixes related to 
- https://github.com/FEniCS/dolfinx/pull/1888
- https://github.com/FEniCS/dolfinx/pull/1894
- https://github.com/FEniCS/dolfinx/pull/1899
> fixes due to changes in dolfinx

- python/demos/nitsche_unbiased_demo.py
- python/dolfinx_contact/unbiased/nitsche_unbiased.py
Improved linear solver options for the unbiased Nitsche method
> improved solver options

- python/demos/Makefile
- python/demos/demo_nitsche_unbiased.py
- python/demos/visualize_iterations.py
- python/dolfinx_contact/newton_solver.py
- python/dolfinx_contact/unbiased/nitsche_unbiased.py
Tweaking solver parameters
A Makefile for generating loads of data
New option to print solver output to file (default is print to terminal)
> Various updates to unbiased demo

- .github/workflows/sonarcloud.yml
- cpp/coefficients.cpp
- cpp/coefficients.h
- python/tests/test_coeffs.py
- Now works on sub-spaces
- Performance improvements in tests by using Expression instead of eval.
> Fix packing of coefficients

- .github/workflows/sonarcloud.yml
- cpp/Contact.h
- cpp/coefficients.cpp
- cpp/contact_kernels.hpp
- cpp/geometric_quantities.cpp
- cpp/utils.cpp
- cpp/utils.h
- python/dolfinx_contact/wrappers.cpp
Also removed the last if-statements from inside the one-sided kernels.
> Unify integration nomenclature for unbiased and 1-sided

- .github/workflows/sonarcloud.yml
- python/dolfinx_contact/helpers.py
- python/tests/test_unbiased.py
* more readable version of ufl form
* two versions of ufl form using R_minus and R_plus, respectively
> improve unbiased test

- .github/workflows/sonarcloud.yml
- .github/workflows/test-app.yml
- cpp/CMakeLists.txt
- cpp/Contact.cpp
- cpp/Contact.h
- cpp/QuadratureRule.cpp
- cpp/QuadratureRule.h
- cpp/coefficients.cpp
- cpp/coefficients.h
- cpp/contact_kernels.hpp
- python/dolfinx_contact/wrappers.cpp
- python/setup.py
- python/tests/test_coeffs.py
Add our own quadrature rule, as the plan is to deprecate dolfinx_cuas.
made tests pack on non-affine geometries as well.
Added new quadrature class
version bump ->0.4.0
> Update packing of coefficients

- cpp/RayTracing.cpp
- cpp/RayTracing.h
- python/dolfinx_contact/wrappers.cpp
- python/tests/test_raytracing.py
Change input for raytracer to be a normal vector.
Change assumption gdim==tdim
> Updates for raytracing to make it more user friendly

- python/dolfinx_contact/meshing/contact_meshes.py
- python/tests/test_projection.py
- fix bug in test_projection.py as reported by sonar cloud, fix #72 
- use smaller meshes for test
- use meshes with flat surfaces to avoid inaccuracies when closest point is on the edge of an element
> update test projection

- cpp/Contact.cpp
- cpp/Contact.h
- cpp/SubMesh.cpp
- cpp/SubMesh.h
- python/dolfinx_contact/wrappers.cpp
- python/tests/test_packing_contact.py
- python/tests/test_unbiased.py
> update submesh geometry and test packing of u, v

- python/demos/demo_nitsche_unbiased.py
- python/dolfinx_contact/unbiased/nitsche_unbiased.py
> Add lifting of classical integrals to unbiased demo

- cpp/CMakeLists.txt
- cpp/Contact.cpp
- cpp/Contact.h
- cpp/coefficients.cpp
- cpp/contact_kernels.hpp
- cpp/error_handling.cpp
- cpp/error_handling.h
- cpp/utils.cpp
Add custom error handler for common error check. Fix sizes in pack_coefficients
> Minor tweaks

- cpp/utils.cpp
To try to figure out why the code sometimes crash on CI
> Add assert and ensure zero initialization

- .github/workflows/sonarcloud.yml
- .github/workflows/test-app.yml
Latest has not been updated in 7 days, after rewriting of docker build system
> Update docker tags to actually be nightly

- cpp/Contact.cpp
- cpp/Contact.h
- python/dolfinx_contact/wrappers.cpp
> only create one submesh for all tagged surfaces

- cpp/Contact.cpp
- cpp/RayTracing.h
- cpp/utils.h
- python/demos/demo_christmas_tree.py
- python/demos/demo_nitsche_meshties.py
- python/demos/demo_nitsche_unbiased.py
- python/demos/gradual_loading.py
- python/demos/meshtie_convergence.py
- python/dolfinx_contact/helpers.py
- python/dolfinx_contact/meshing/split_box.py
- python/dolfinx_contact/meshtie/nitsche_meshtie.py
- python/dolfinx_contact/one_sided/nitsche_custom.py
- python/dolfinx_contact/one_sided/nitsche_rigid_surface.py
- python/dolfinx_contact/one_sided/nitsche_rigid_surface_custom.py
- python/dolfinx_contact/one_sided/nitsche_ufl.py
- python/dolfinx_contact/one_sided/snes_against_plane.py
- python/dolfinx_contact/parallel_mesh_ghosting.py
- python/dolfinx_contact/plotting.py
- python/dolfinx_contact/unbiased/nitsche_unbiased.py
- python/tests/test_circumradius.py
- python/tests/test_coeffs.py
- python/tests/test_contact_kernels.py
- python/tests/test_dolfinx_custom.py
- python/tests/test_raytracing.py
- python/tests/test_unbiased.py
This is not strictly needed, but clang doesn't like the current code, so to be able to compile on MacOS, I've changed iterators to pointers.
> Span use pointer

- .github/workflows/test-app.yml
- python/demos/box_key_3D.py
- python/demos/demo_christmas_tree_3D.py
- python/demos/demo_nitsche_meshties.py
- python/demos/demo_nitsche_unbiased.py
- python/dolfinx_contact/helpers.py
- python/dolfinx_contact/meshtie/nitsche_meshtie.py
- python/dolfinx_contact/newton_solver.py
- python/dolfinx_contact/one_sided/nitsche_custom.py
- python/dolfinx_contact/one_sided/nitsche_rigid_surface.py
- python/dolfinx_contact/one_sided/nitsche_rigid_surface_custom.py
- python/dolfinx_contact/one_sided/nitsche_ufl.py
- python/dolfinx_contact/one_sided/snes_against_plane.py
- python/dolfinx_contact/unbiased/nitsche_unbiased.py
- reinstate mypy checks
- temporary fix for #131
> reinstate mypy checks

- cpp/Contact.cpp
Fix related to https://github.com/FEniCS/dolfinx/pull/2650
> pattern.assemble() -> pattern.finalize()

- cpp/utils.cpp
Fixes error due to function not returning a value
> fix warning

- cpp/demos/meshtie/linear_elasticity.py
- python/demos/oxford/blocks_nitsche.py
See https://github.com/FEniCS/basix/pull/708
> Changes in line with updates to basix
